/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.ufmt.poo.bancoDeBancas.ui;

import br.ufmt.poo.bancoDeBancas.service.PessoaService;
import br.ufmt.poo.bancoDeBancas.service.impl.PessoaServiceImpl;
import br.ufmt.poo.bancoDeBancas.ui.dto.PessoaDTO;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aluno
 */
public class PessoaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PessoaJPanel
     */
    public PessoaJPanel() {
        initComponents();
        atualizarTabela();
    }
    
    private void atualizarTabela() {
        PessoaService service = new PessoaServiceImpl();
        List<PessoaDTO> lista = service.listar();
        
        DefaultTableModel dfm = (DefaultTableModel) tabelaJTable.getModel();
        int linhas = dfm.getRowCount();
        for (int i = 0; i < linhas; i++) {
            dfm.removeRow(0);
        }
        
        for (PessoaDTO pessoaDTO : lista) {
            Object[] linha = new Object[3];
            linha[0] = pessoaDTO.getId();
            linha[1] = pessoaDTO.getNome();
            linha[2] = pessoaDTO.getCpf();
            
            dfm.addRow(linha);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idJLabel = new javax.swing.JLabel();
        nomeJLabel = new javax.swing.JLabel();
        cpfJLabel = new javax.swing.JLabel();
        idJTextField = new javax.swing.JTextField();
        nomeJTextField = new javax.swing.JTextField();
        cpfJFormattedTextField = new javax.swing.JFormattedTextField();
        salvarJButton = new javax.swing.JButton();
        cancelarJButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaJTable = new javax.swing.JTable();
        editarJButton = new javax.swing.JButton();
        removerJButton = new javax.swing.JButton();

        idJLabel.setText("ID:");

        nomeJLabel.setText("Nome:");

        cpfJLabel.setText("CPF:");

        idJTextField.setEditable(false);

        try {
            cpfJFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        salvarJButton.setText("Salvar");
        salvarJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarJButtonActionPerformed(evt);
            }
        });

        cancelarJButton.setText("Cancelar");
        cancelarJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarJButtonActionPerformed(evt);
            }
        });

        tabelaJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "CPF"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaJTable);

        editarJButton.setText("Editar");
        editarJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarJButtonActionPerformed(evt);
            }
        });

        removerJButton.setText("Remover");
        removerJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(nomeJLabel)
                        .addComponent(cpfJLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(idJLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(removerJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(editarJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nomeJTextField)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 411, Short.MAX_VALUE)
                    .addComponent(idJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cpfJFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(salvarJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelarJButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idJLabel)
                    .addComponent(idJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeJLabel)
                    .addComponent(nomeJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cpfJLabel)
                    .addComponent(cpfJFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salvarJButton)
                    .addComponent(cancelarJButton))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(editarJButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(removerJButton)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cancelarJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarJButtonActionPerformed
        // TODO add your handling code here:
        idJTextField.setText("");
        nomeJTextField.setText("");
        cpfJFormattedTextField.setValue(null);
    }//GEN-LAST:event_cancelarJButtonActionPerformed

    private void salvarJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarJButtonActionPerformed
        // TODO add your handling code here:
        String id = idJTextField.getText();
        String nome = nomeJTextField.getText();
        String cpf = cpfJFormattedTextField.getText();
        
        PessoaDTO dto = new PessoaDTO(id, nome, cpf);
        
        // enviando para a service
        PessoaService service = new PessoaServiceImpl();
        try {
            service.salvar(dto);
            JOptionPane.showMessageDialog(this, "Salvo com Sucesso!");
            cancelarJButtonActionPerformed(evt);
            atualizarTabela();
        } catch(Exception erro) {
            JOptionPane.showMessageDialog(this, erro.getMessage());
        }
    }//GEN-LAST:event_salvarJButtonActionPerformed

    private void removerJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerJButtonActionPerformed
        // TODO add your handling code here:
        int total = tabelaJTable.getSelectedRowCount();
        if(total <= 0){
            JOptionPane.showMessageDialog(tabelaJTable, "Por favor selecione as linhas a serem removidas!");
            return;
        }
        try {
            int[] linhas = tabelaJTable.getSelectedRows();
            PessoaService service = new PessoaServiceImpl();
            for (int linha : linhas) {
                String id = (String) tabelaJTable.getValueAt(linha, 0);
                PessoaDTO dto = new PessoaDTO(id, null, null);
                service.remover(dto);
            }
            JOptionPane.showMessageDialog(tabelaJTable, "Registros removidos com sucesso!");
            atualizarTabela();
        } catch (Exception erro) {
            erro.printStackTrace();
            JOptionPane.showMessageDialog(tabelaJTable, erro.getMessage());
        }
    }//GEN-LAST:event_removerJButtonActionPerformed

    private void editarJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarJButtonActionPerformed
        // TODO add your handling code here:
        int total = tabelaJTable.getSelectedRowCount();
        if(total != 1){
            JOptionPane.showMessageDialog(tabelaJTable, "Por favor selecione somente 1 linha para editar!");
            return;
        }
        int linha = tabelaJTable.getSelectedRow();
        String id = (String) tabelaJTable.getValueAt(linha, 0);
        String nome = (String) tabelaJTable.getValueAt(linha, 1);
        String cpf = (String) tabelaJTable.getValueAt(linha, 2);
        
        idJTextField.setText(id);
        nomeJTextField.setText(nome);
        cpfJFormattedTextField.setText(cpf);
    }//GEN-LAST:event_editarJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelarJButton;
    private javax.swing.JFormattedTextField cpfJFormattedTextField;
    private javax.swing.JLabel cpfJLabel;
    private javax.swing.JButton editarJButton;
    private javax.swing.JLabel idJLabel;
    private javax.swing.JTextField idJTextField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nomeJLabel;
    private javax.swing.JTextField nomeJTextField;
    private javax.swing.JButton removerJButton;
    private javax.swing.JButton salvarJButton;
    private javax.swing.JTable tabelaJTable;
    // End of variables declaration//GEN-END:variables
}
